### ISSUE TITLE
SimpleTransformer should work for arrays as well as scalar values

### ISSUE THREAD

**Issue by kathryn-baker** [MatInGit/lume-deployment#11]

**Comment by MatInGit** [comment]
Implemented, added a (test)[https://github.com/MatInGit/lume-deployment/blob/c35aaaf31e88749f7b7390130cb12dfa2a6805c3/tests/test_transformers.py#L70] I am not to familiar with sympy matrix syntax but it would be worth adding more test just to serve as examples.
